# Generated by Django 5.2 on 2025-04-08 00:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='about_banners/')),
                ('historia_titulo', models.CharField(max_length=100)),
                ('historia_conteudo', ckeditor.fields.RichTextField()),
                ('missao_titulo', models.CharField(max_length=100)),
                ('missao_conteudo', ckeditor.fields.RichTextField()),
                ('mapa_embed', models.TextField(help_text='Código iframe do Google Maps')),
                ('botao_texto', models.CharField(max_length=50)),
                ('botao_link', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Página Sobre',
                'verbose_name_plural': 'Página Sobre',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='team_photos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['ordem'],
            },
        ),
    ]
